import { useState, useEffect } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { generateQuestions, isGeminiReady } from '../utils/gemini';
import { motion } from 'framer-motion';
import { Share } from '@capacitor/share';
import { Clipboard } from '@capacitor/clipboard';
import { Haptics, ImpactStyle } from '@capacitor/haptics';
import { Share2, Copy, Check } from 'lucide-react';

export default function GenerateQuestionsPage() {
  const location = useLocation();
  const navigate = useNavigate();
  const { extractedText, fileName } = location.state || {};
  const [questions, setQuestions] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (!extractedText) {
      navigate('/');
      return;
    }
    if (!isGeminiReady()) {
      setError('Please set your Gemini API key first!');
      setLoading(false);
      return;
    }

    const fetchQuestions = async () => {
      try {
        const qs = await generateQuestions(extractedText);
        setQuestions(qs);
      } catch (err) {
        setError('Failed to generate questions: ' + err.message);
      }
      setLoading(false);
    };
    fetchQuestions();
  }, [extractedText, navigate]);

  const triggerHaptic = async () => {
    try { await Haptics.impact({ style: ImpactStyle.Light }); } catch (e) {}
  };

  const handleShare = async () => {
    triggerHaptic();
    const textToShare = questions.map((q, i) => `${i + 1}. ${q}`).join('\n\n');
    try {
      await Share.share({
        title: `MindMate AI - Practice Questions`,
        text: `Check out these exam questions for ${fileName}:\n\n${textToShare}\n\nGenerated by MindMate AI 🚀`,
        dialogTitle: 'Share Questions',
      });
    } catch (error) {
      console.error('Error sharing:', error);
    }
  };

  const handleCopy = async () => {
    triggerHaptic();
    const textToCopy = questions.map((q, i) => `${i + 1}. ${q}`).join('\n\n');
    try {
      await Clipboard.write({ string: textToCopy });
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      console.error('Error copying:', error);
    }
  };

  if (loading) {
    return (
      <motion.div 
        className="page-container"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
      >
        <div className="loading-container">
          <div className="loading-spinner"></div>
          <p className="loading-text">Generating important questions... 🧠</p>
        </div>
      </motion.div>
    );
  }

  if (error) {
    return (
      <div className="page-container">
        <button className="back-btn" onClick={() => navigate('/')}>← Back Home</button>
        <div className="info-page">
          <div className="info-card">
            <h1>⚠️ Error</h1>
            <p>{error}</p>
          </div>
        </div>
      </div>
    );
  }

  const containerVariants = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: { staggerChildren: 0.1 }
    }
  };

  const itemVariants = {
    hidden: { opacity: 0, x: -20 },
    show: { opacity: 1, x: 0, transition: { type: "spring", stiffness: 200 } }
  };

  return (
    <div className="page-container">
      <button className="back-btn" onClick={() => navigate('/')}>← Back Home</button>
      <motion.div 
        className="page-header"
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
      >
        <h1>🧠 Important Questions</h1>
        <p>From: {fileName}</p>
      </motion.div>
      
      <motion.div 
        className="questions-page-card" style={{ position: 'relative' }}
        initial={{ opacity: 0, scale: 0.95, y: 30 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        transition={{ type: "spring", stiffness: 100, damping: 20 }}
      >
        <div className="card-top-image" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', paddingRight: '20px' }}>
          <img src="/images/logo.svg" alt="MindMate AI" style={{ height: '60px', width: 'auto' }} />
          <div className="action-buttons">
            <button className="action-btn" onClick={handleCopy} title="Copy to clipboard">
              {copied ? <Check size={20} color="#22c55e" /> : <Copy size={20} />}
            </button>
            <button className="action-btn" onClick={handleShare} title="Share Questions">
              <Share2 size={20} />
            </button>
          </div>
        </div>
        <motion.ol 
          className="questions-list"
          variants={containerVariants}
          initial="hidden"
          animate="show"
        >
          {questions.map((q, idx) => (
            <motion.li key={idx} variants={itemVariants}>
              {q}
            </motion.li>
          ))}
        </motion.ol>
      </motion.div>
    </div>
  );
}
