import { useState, useEffect } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { summarizeText, summarizeInKannada, isGeminiReady } from '../utils/gemini';
import { Share } from '@capacitor/share';
import { Clipboard } from '@capacitor/clipboard';
import { Share2, Copy, Check } from 'lucide-react';
import { motion } from 'framer-motion';

export default function SummarizePage() {
  const location = useLocation();
  const navigate = useNavigate();
  const { extractedText, fileName } = location.state || {};
  const [englishSummary, setEnglishSummary] = useState('');
  const [kannadaSummary, setKannadaSummary] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [copiedEng, setCopiedEng] = useState(false);
  const [copiedKan, setCopiedKan] = useState(false);

  useEffect(() => {
    if (!extractedText) {
      navigate('/');
      return;
    }
    if (!isGeminiReady()) {
      setError('Please set your Gemini API key first!');
      setLoading(false);
      return;
    }

    const fetchSummaries = async () => {
      try {
        const [eng, kan] = await Promise.all([
          summarizeText(extractedText),
          summarizeInKannada(extractedText)
        ]);
        setEnglishSummary(eng);
        setKannadaSummary(kan);
      } catch (err) {
        setError('Failed to generate summaries: ' + err.message);
      }
      setLoading(false);
    };
    fetchSummaries();
  }, [extractedText, navigate]);

  const handleShare = async (title, text) => {
    try {
      await Share.share({
        title: `MindMate AI - ${title}`,
        text: `${title}\n\n${text}\n\nGenerated by MindMate AI`,
        dialogTitle: 'Share your Summary',
      });
    } catch (error) {
      console.error('Error sharing:', error);
    }
  };

  const handleCopy = async (text, isEng) => {
    try {
      await Clipboard.write({
        string: text
      });
      if (isEng) {
        setCopiedEng(true);
        setTimeout(() => setCopiedEng(false), 2000);
      } else {
        setCopiedKan(true);
        setTimeout(() => setCopiedKan(false), 2000);
      }
    } catch (error) {
      console.error('Error copying:', error);
    }
  };

  if (loading) {
    return (
      <motion.div 
        className="page-container"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
      >
        <div className="loading-container">
          <div className="loading-spinner"></div>
          <p className="loading-text">Summarizing your notes in English & Kannada... 🚀</p>
        </div>
      </motion.div>
    );
  }

  if (error) {
    return (
      <div className="page-container">
        <button className="back-btn" onClick={() => navigate('/')}>← Back Home</button>
        <div className="info-page">
          <div className="info-card">
            <h1>⚠️ Error</h1>
            <p>{error}</p>
          </div>
        </div>
      </div>
    );
  }

  const cardVariants = {
    hidden: { opacity: 0, y: 50, scale: 0.95 },
    visible: { 
      opacity: 1, 
      y: 0, 
      scale: 1,
      transition: { type: 'spring', damping: 20, stiffness: 100 }
    }
  };

  return (
    <div className="page-container">
      <button className="back-btn" onClick={() => navigate('/')}>← Back Home</button>
      <div className="page-header">
        <h1>📝 Summary</h1>
        <p>From: {fileName}</p>
      </div>
      <motion.div 
        className="summary-cards"
        initial="hidden"
        animate="visible"
        variants={{ visible: { transition: { staggerChildren: 0.2 } } }}
      >
        <motion.div className="summary-card" variants={cardVariants}>
          <div className="card-header-actions">
            <h2>🇺🇸 English Summary</h2>
            <div className="action-buttons">
              <button 
                className="action-btn" 
                onClick={() => handleCopy(englishSummary, true)}
                title="Copy to clipboard"
              >
                {copiedEng ? <Check size={20} color="#22c55e" /> : <Copy size={20} />}
              </button>
              <button 
                className="action-btn" 
                onClick={() => handleShare('English Summary', englishSummary)}
                title="Share via other apps"
              >
                <Share2 size={20} />
              </button>
            </div>
          </div>
          <div className="summary-text">{englishSummary}</div>
        </motion.div>

        <motion.div className="summary-card" variants={cardVariants}>
          <div className="card-header-actions">
            <h2>🇮🇳 ಕನ್ನಡ ಸಾರಾಂಶ</h2>
            <div className="action-buttons">
              <button 
                className="action-btn" 
                onClick={() => handleCopy(kannadaSummary, false)}
                title="Copy to clipboard"
              >
                {copiedKan ? <Check size={20} color="#22c55e" /> : <Copy size={20} />}
              </button>
              <button 
                className="action-btn" 
                onClick={() => handleShare('Kannada Summary', kannadaSummary)}
                title="Share via other apps"
              >
                <Share2 size={20} />
              </button>
            </div>
          </div>
          <div className="summary-text">{kannadaSummary}</div>
        </motion.div>
      </motion.div>
    </div>
  );
}
